#!/usr/bin/env bash

## KNOWN ISSUE
#
# This code results in the signing key passphrase showing up in the build
# console. To this I say "fuck it." The process for hiding it was so broken
# and the security implications were minimal. I decided it was not worth the
# effort. At least it's not in source control.

set -ex

if [ ! -r /secrets/signing_key_passphrase ]; then
  echo 'File not found: /secrets/signing_key_passphrase'
  exit 1
fi

if [ ! -r /secrets/signing_subkey_fingerprint ]; then
  echo 'File not found: /secrets/signing_subkey_fingerprint'
  exit 1
fi

SIGNING_KEY_FINGERPRINT=$(cat /secrets/signing_subkey_fingerprint)
SIGNING_KEY_PASSPHRASE=$(cat /secrets/signing_key_passphrase)

cd /build
apt-get source imagemagick

UPSTREAM_DEB_VERSION=$(apt-cache policy imagemagick | grep 'Candidate:' | awk '{print $2}')
UPSTREAM_VERSION=$(find . -name '*.orig.tar.xz' | sed 's/\(^\.\/imagemagick_\|\.orig.*\)//g')
EVERTRUE_VERSION=$(cat /build/build-debian/evertrue-version)
UPSTREAM_VERSION_WITH_EPOCH=$(echo $UPSTREAM_DEB_VERSION | sed 's/ubuntu.*//')

rm -rf /build/imagemagick-${UPSTREAM_VERSION}/debian
mkdir /build/imagemagick-${UPSTREAM_VERSION}/debian
cp /build/build-debian/control /build/imagemagick-${UPSTREAM_VERSION}/debian/

# e.g. 8:6.9.6-4evertrue2.0
PACKAGE_VERSION="${UPSTREAM_VERSION_WITH_EPOCH}evertrue${EVERTRUE_VERSION}"

# Make a bullshit changelog because one is required
cat > /build/imagemagick-${UPSTREAM_VERSION}/debian/changelog << EOF
imagemagick-et (${PACKAGE_VERSION}) stable; urgency=medium

  [ Evertrue DevOps ]
  * Rebuilt for new upstream version

 -- Evertrue DevOps <devops@evertrue.com>  $(date +"%a, %d %b %Y %H:%M:%S %z")
EOF

# PACKAGE_VERSION=`dpkg-parsechangelog --show-field Version`
PACKAGE_VERSION_NO_EPOCH=$(echo $PACKAGE_VERSION | sed s/.*:// )

cd /build/imagemagick-${UPSTREAM_VERSION}

# Do the build
./configure \
  --prefix=/opt/ImageMagick-6 \
  --without-x

make

checkinstall -D \
  --install=no \
  --fstrans=no \
  --pakdir "$PWD/.." \
  --pkgname imagemagick-et \
  --backup=no \
  --deldoc=yes \
  --deldesc=yes \
  --delspec=yes \
  --default \
  --pkgversion "$PACKAGE_VERSION"

gpg --import /secrets/evertrue_apt_pub.gpg
gpg --allow-secret-key-import --import /secrets/evertrue_apt_sec.gpg

dpkg-sig \
  -k $SIGNING_KEY_FINGERPRINT \
  -g "--passphrase ${SIGNING_KEY_PASSPHRASE} --batch --no-use-agent" \
  --sign evertrue \
  "$PWD/../imagemagick-et_${PACKAGE_VERSION_NO_EPOCH}-1_amd64.deb"

# # Upload built artifacts to S3
deb-s3 upload \
  --arch amd64 \
  --codename xenial \
  --sign $SIGNING_KEY_FINGERPRINT \
  --gpg-options "--passphrase ${SIGNING_KEY_PASSPHRASE} --batch --no-use-agent" \
  --prefix debian-repo \
  --bucket ops.evertrue.com \
  "$PWD/../imagemagick-et_${PACKAGE_VERSION_NO_EPOCH}-1_amd64.deb"

rm -rf /opt/ImageMagick-6
rm -f "$PWD/../imagemagick-et_${PACKAGE_VERSION_NO_EPOCH}-1_amd64.deb"
